services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: wrenly-sql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SQL_SERVER_PASSWORD}
    ports:
      - "${SQL_SERVER_PORT}:1433"
    networks:
      - wrenly-network
    volumes:
      - wrenly_sql:/var/opt/mssql

  backend:
    build:
      context: .
      dockerfile: apps/api/Wrenly.Api/Dockerfile
    container_name: wrenly-api
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ConnectionStrings__AuthDb=Server=sqlserver;Database=Wrenly.Auth;User Id=sa;Password=${SQL_SERVER_PASSWORD};TrustServerCertificate=True
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ${USERPROFILE}\.aspnet\https:/https:ro
    depends_on:
      - sqlserver
    networks:
      - wrenly-network

networks:
  wrenly-network:
    driver: bridge

volumes:
  wrenly_sql: